package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-30 16:21:58 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BankInfo generated by hbm2java
 */
@Entity
@Table(name = "bank_info", schema = "public")
public class BankInfo implements java.io.Serializable {

	private String bankCode;
	private String bankFullName;
	private String bankSimpleName;

	public BankInfo() {
	}

	public BankInfo(String bankCode) {
		this.bankCode = bankCode;
	}

	public BankInfo(String bankCode, String bankFullName, String bankSimpleName) {
		this.bankCode = bankCode;
		this.bankFullName = bankFullName;
		this.bankSimpleName = bankSimpleName;
	}

	@Id

	@Column(name = "bank_code", unique = true, nullable = false, length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "bank_full_name", length = 128)
	public String getBankFullName() {
		return this.bankFullName;
	}

	public void setBankFullName(String bankFullName) {
		this.bankFullName = bankFullName;
	}

	@Column(name = "bank_simple_name", length = 64)
	public String getBankSimpleName() {
		return this.bankSimpleName;
	}

	public void setBankSimpleName(String bankSimpleName) {
		this.bankSimpleName = bankSimpleName;
	}

}
