package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-16 13:34:04 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DataTransBack generated by hbm2java
 */
@Entity
@Table(name = "data_trans_back", schema = "public")
public class DataTransBack implements java.io.Serializable {

	private DataTransBackId id;
	private BigDecimal rowsCount;

	public DataTransBack() {
	}

	public DataTransBack(DataTransBackId id) {
		this.id = id;
	}

	public DataTransBack(DataTransBackId id, BigDecimal rowsCount) {
		this.id = id;
		this.rowsCount = rowsCount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "transUuid", column = @Column(name = "trans_uuid", nullable = false, length = 36)),
			@AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", nullable = false, length = 4)),
			@AttributeOverride(name = "tableCode", column = @Column(name = "table_code", nullable = false, length = 4)) })
	public DataTransBackId getId() {
		return this.id;
	}

	public void setId(DataTransBackId id) {
		this.id = id;
	}

	@Column(name = "rows_count", precision = 131089, scale = 0)
	public BigDecimal getRowsCount() {
		return this.rowsCount;
	}

	public void setRowsCount(BigDecimal rowsCount) {
		this.rowsCount = rowsCount;
	}

}
