package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-9 12:39:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataCorePrivateAccountInfo generated by hbm2java
 */
@Entity
@Table(name = "data_core_private_account_info", schema = "public")
public class DataCorePrivateAccountInfo implements java.io.Serializable {

	private DataCorePrivateAccountInfoId id;
	private String privateAccountName;
	private String privateCustomId;
	private String privateCardNo;
	private Date privateOpenDat;
	private Date privateCloseDat;
	private String privateAcountStatus;
	private Date timepoint;

	public DataCorePrivateAccountInfo() {
	}

	public DataCorePrivateAccountInfo(DataCorePrivateAccountInfoId id) {
		this.id = id;
	}

	public DataCorePrivateAccountInfo(DataCorePrivateAccountInfoId id, String privateAccountName,
			String privateCustomId, String privateCardNo, Date privateOpenDat, Date privateCloseDat,
			String privateAcountStatus, Date timepoint) {
		this.id = id;
		this.privateAccountName = privateAccountName;
		this.privateCustomId = privateCustomId;
		this.privateCardNo = privateCardNo;
		this.privateOpenDat = privateOpenDat;
		this.privateCloseDat = privateCloseDat;
		this.privateAcountStatus = privateAcountStatus;
		this.timepoint = timepoint;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "privateAccountId", column = @Column(name = "private_account_id", nullable = false, length = 128)),
			@AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", nullable = false, length = 4)) })
	public DataCorePrivateAccountInfoId getId() {
		return this.id;
	}

	public void setId(DataCorePrivateAccountInfoId id) {
		this.id = id;
	}

	@Column(name = "private_account_name", length = 256)
	public String getPrivateAccountName() {
		return this.privateAccountName;
	}

	public void setPrivateAccountName(String privateAccountName) {
		this.privateAccountName = privateAccountName;
	}

	@Column(name = "private_custom_id", length = 128)
	public String getPrivateCustomId() {
		return this.privateCustomId;
	}

	public void setPrivateCustomId(String privateCustomId) {
		this.privateCustomId = privateCustomId;
	}

	@Column(name = "private_card_no", length = 64)
	public String getPrivateCardNo() {
		return this.privateCardNo;
	}

	public void setPrivateCardNo(String privateCardNo) {
		this.privateCardNo = privateCardNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "private_open_dat", length = 35)
	public Date getPrivateOpenDat() {
		return this.privateOpenDat;
	}

	public void setPrivateOpenDat(Date privateOpenDat) {
		this.privateOpenDat = privateOpenDat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "private_close_dat", length = 35)
	public Date getPrivateCloseDat() {
		return this.privateCloseDat;
	}

	public void setPrivateCloseDat(Date privateCloseDat) {
		this.privateCloseDat = privateCloseDat;
	}

	@Column(name = "private_acount_status", length = 32)
	public String getPrivateAcountStatus() {
		return this.privateAcountStatus;
	}

	public void setPrivateAcountStatus(String privateAcountStatus) {
		this.privateAcountStatus = privateAcountStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timepoint", length = 35)
	public Date getTimepoint() {
		return this.timepoint;
	}

	public void setTimepoint(Date timepoint) {
		this.timepoint = timepoint;
	}

}
