package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-2 21:10:43 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DataCorePrivateCustomBase generated by hbm2java
 */
@Entity
@Table(name = "data_core_private_custom_base", schema = "public")
public class DataCorePrivateCustomBase implements java.io.Serializable {

	private DataCorePrivateCustomBaseId id;
	private String privateCustomName;
	private String privateCompany;
	private String privatePostAddress;
	private String privateWorkAddress;
	private String privateIdCard;

	public DataCorePrivateCustomBase() {
	}

	public DataCorePrivateCustomBase(DataCorePrivateCustomBaseId id) {
		this.id = id;
	}

	public DataCorePrivateCustomBase(DataCorePrivateCustomBaseId id, String privateCustomName, String privateCompany,
			String privatePostAddress, String privateWorkAddress, String privateIdCard) {
		this.id = id;
		this.privateCustomName = privateCustomName;
		this.privateCompany = privateCompany;
		this.privatePostAddress = privatePostAddress;
		this.privateWorkAddress = privateWorkAddress;
		this.privateIdCard = privateIdCard;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", nullable = false, length = 4)),
			@AttributeOverride(name = "privateCustomId", column = @Column(name = "private_custom_id", nullable = false, length = 128)) })
	public DataCorePrivateCustomBaseId getId() {
		return this.id;
	}

	public void setId(DataCorePrivateCustomBaseId id) {
		this.id = id;
	}

	@Column(name = "private_custom_name", length = 256)
	public String getPrivateCustomName() {
		return this.privateCustomName;
	}

	public void setPrivateCustomName(String privateCustomName) {
		this.privateCustomName = privateCustomName;
	}

	@Column(name = "private_company", length = 256)
	public String getPrivateCompany() {
		return this.privateCompany;
	}

	public void setPrivateCompany(String privateCompany) {
		this.privateCompany = privateCompany;
	}

	@Column(name = "private_post_address", length = 512)
	public String getPrivatePostAddress() {
		return this.privatePostAddress;
	}

	public void setPrivatePostAddress(String privatePostAddress) {
		this.privatePostAddress = privatePostAddress;
	}

	@Column(name = "private_work_address", length = 512)
	public String getPrivateWorkAddress() {
		return this.privateWorkAddress;
	}

	public void setPrivateWorkAddress(String privateWorkAddress) {
		this.privateWorkAddress = privateWorkAddress;
	}

	@Column(name = "private_id_card", length = 64)
	public String getPrivateIdCard() {
		return this.privateIdCard;
	}

	public void setPrivateIdCard(String privateIdCard) {
		this.privateIdCard = privateIdCard;
	}

}
