package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-5 2:10:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataCorePublicAcountInfo generated by hbm2java
 */
@Entity
@Table(name = "data_core_public_acount_info", schema = "public")
public class DataCorePublicAcountInfo implements java.io.Serializable {

	private DataCorePublicAcountInfoId id;
	private String publicAccountName;
	private String publicAccountStatus;
	private Date publicOpenDat;
	private Date publicCloseDat;
	private String publicCustomId;

	public DataCorePublicAcountInfo() {
	}

	public DataCorePublicAcountInfo(DataCorePublicAcountInfoId id) {
		this.id = id;
	}

	public DataCorePublicAcountInfo(DataCorePublicAcountInfoId id, String publicAccountName, String publicAccountStatus,
			Date publicOpenDat, Date publicCloseDat, String publicCustomId) {
		this.id = id;
		this.publicAccountName = publicAccountName;
		this.publicAccountStatus = publicAccountStatus;
		this.publicOpenDat = publicOpenDat;
		this.publicCloseDat = publicCloseDat;
		this.publicCustomId = publicCustomId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", nullable = false, length = 4)),
			@AttributeOverride(name = "publicAccountId", column = @Column(name = "public_account_id", nullable = false, length = 128)) })
	public DataCorePublicAcountInfoId getId() {
		return this.id;
	}

	public void setId(DataCorePublicAcountInfoId id) {
		this.id = id;
	}

	@Column(name = "public_account_name", length = 256)
	public String getPublicAccountName() {
		return this.publicAccountName;
	}

	public void setPublicAccountName(String publicAccountName) {
		this.publicAccountName = publicAccountName;
	}

	@Column(name = "public_account_status", length = 32)
	public String getPublicAccountStatus() {
		return this.publicAccountStatus;
	}

	public void setPublicAccountStatus(String publicAccountStatus) {
		this.publicAccountStatus = publicAccountStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "public_open_dat", length = 35)
	public Date getPublicOpenDat() {
		return this.publicOpenDat;
	}

	public void setPublicOpenDat(Date publicOpenDat) {
		this.publicOpenDat = publicOpenDat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "public_close_dat", length = 35)
	public Date getPublicCloseDat() {
		return this.publicCloseDat;
	}

	public void setPublicCloseDat(Date publicCloseDat) {
		this.publicCloseDat = publicCloseDat;
	}

	@Column(name = "public_custom_id", length = 128)
	public String getPublicCustomId() {
		return this.publicCustomId;
	}

	public void setPublicCustomId(String publicCustomId) {
		this.publicCustomId = publicCustomId;
	}

}
