package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-2 21:10:43 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DataCorePublicAccountTradeDetailId generated by hbm2java
 */
@Embeddable
public class DataCorePublicAccountTradeDetailId implements java.io.Serializable {

	private String bankCode;
	private String publicAccountId;
	private String publicTradeSeq;
	private Date publicTradeDat;

	public DataCorePublicAccountTradeDetailId() {
	}

	public DataCorePublicAccountTradeDetailId(String bankCode, String publicAccountId, String publicTradeSeq,
			Date publicTradeDat) {
		this.bankCode = bankCode;
		this.publicAccountId = publicAccountId;
		this.publicTradeSeq = publicTradeSeq;
		this.publicTradeDat = publicTradeDat;
	}

	@Column(name = "bank_code", nullable = false, length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "public_account_id", nullable = false, length = 128)
	public String getPublicAccountId() {
		return this.publicAccountId;
	}

	public void setPublicAccountId(String publicAccountId) {
		this.publicAccountId = publicAccountId;
	}

	@Column(name = "public_trade_seq", nullable = false, length = 128)
	public String getPublicTradeSeq() {
		return this.publicTradeSeq;
	}

	public void setPublicTradeSeq(String publicTradeSeq) {
		this.publicTradeSeq = publicTradeSeq;
	}

	@Column(name = "public_trade_dat", nullable = false, length = 35)
	public Date getPublicTradeDat() {
		return this.publicTradeDat;
	}

	public void setPublicTradeDat(Date publicTradeDat) {
		this.publicTradeDat = publicTradeDat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataCorePublicAccountTradeDetailId))
			return false;
		DataCorePublicAccountTradeDetailId castOther = (DataCorePublicAccountTradeDetailId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getPublicAccountId() == castOther.getPublicAccountId())
						|| (this.getPublicAccountId() != null && castOther.getPublicAccountId() != null
								&& this.getPublicAccountId().equals(castOther.getPublicAccountId())))
				&& ((this.getPublicTradeSeq() == castOther.getPublicTradeSeq())
						|| (this.getPublicTradeSeq() != null && castOther.getPublicTradeSeq() != null
								&& this.getPublicTradeSeq().equals(castOther.getPublicTradeSeq())))
				&& ((this.getPublicTradeDat() == castOther.getPublicTradeDat())
						|| (this.getPublicTradeDat() != null && castOther.getPublicTradeDat() != null
								&& this.getPublicTradeDat().equals(castOther.getPublicTradeDat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getPublicAccountId() == null ? 0 : this.getPublicAccountId().hashCode());
		result = 37 * result + (getPublicTradeSeq() == null ? 0 : this.getPublicTradeSeq().hashCode());
		result = 37 * result + (getPublicTradeDat() == null ? 0 : this.getPublicTradeDat().hashCode());
		return result;
	}

}
