package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-2 15:03:25 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDept generated by hbm2java
 */
@Entity
@Table(name = "sys_dept", schema = "public")
public class SysDept implements java.io.Serializable {

	private String deptUuid;
	private String deptName;
	private BigDecimal userNum;
	private String deptType;

	public SysDept() {
	}

	public SysDept(String deptUuid) {
		this.deptUuid = deptUuid;
	}

	public SysDept(String deptUuid, String deptName, BigDecimal userNum, String deptType) {
		this.deptUuid = deptUuid;
		this.deptName = deptName;
		this.userNum = userNum;
		this.deptType = deptType;
	}

	@Id

	@Column(name = "dept_uuid", unique = true, nullable = false, length = 36)
	public String getDeptUuid() {
		return this.deptUuid;
	}

	public void setDeptUuid(String deptUuid) {
		this.deptUuid = deptUuid;
	}

	@Column(name = "dept_name", length = 128)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "user_num", precision = 131089, scale = 0)
	public BigDecimal getUserNum() {
		return this.userNum;
	}

	public void setUserNum(BigDecimal userNum) {
		this.userNum = userNum;
	}

	@Column(name = "dept_type", length = 4)
	public String getDeptType() {
		return this.deptType;
	}

	public void setDeptType(String deptType) {
		this.deptType = deptType;
	}

}
