package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-16 13:34:04 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserViewResultLogId generated by hbm2java
 */
@Embeddable
public class UserViewResultLogId implements java.io.Serializable {

	private String userId;
	private String billUuid;
	private Date viewDat;

	public UserViewResultLogId() {
	}

	public UserViewResultLogId(String userId, String billUuid, Date viewDat) {
		this.userId = userId;
		this.billUuid = billUuid;
		this.viewDat = viewDat;
	}

	@Column(name = "user_id", nullable = false, length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "bill_uuid", nullable = false, length = 36)
	public String getBillUuid() {
		return this.billUuid;
	}

	public void setBillUuid(String billUuid) {
		this.billUuid = billUuid;
	}

	@Column(name = "view_dat", nullable = false, length = 35)
	public Date getViewDat() {
		return this.viewDat;
	}

	public void setViewDat(Date viewDat) {
		this.viewDat = viewDat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserViewResultLogId))
			return false;
		UserViewResultLogId castOther = (UserViewResultLogId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getBillUuid() == castOther.getBillUuid()) || (this.getBillUuid() != null
						&& castOther.getBillUuid() != null && this.getBillUuid().equals(castOther.getBillUuid())))
				&& ((this.getViewDat() == castOther.getViewDat()) || (this.getViewDat() != null
						&& castOther.getViewDat() != null && this.getViewDat().equals(castOther.getViewDat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getBillUuid() == null ? 0 : this.getBillUuid().hashCode());
		result = 37 * result + (getViewDat() == null ? 0 : this.getViewDat().hashCode());
		return result;
	}

}
