package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-2 15:03:25 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserViewResultLog generated by hbm2java
 */
@Entity
@Table(name = "user_view_result_log", schema = "public")
public class UserViewResultLog implements java.io.Serializable {

	private UserViewResultLogId id;
	private String deptId;
	private String userIp;

	public UserViewResultLog() {
	}

	public UserViewResultLog(UserViewResultLogId id) {
		this.id = id;
	}

	public UserViewResultLog(UserViewResultLogId id, String deptId, String userIp) {
		this.id = id;
		this.deptId = deptId;
		this.userIp = userIp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 36)),
			@AttributeOverride(name = "billUuid", column = @Column(name = "bill_uuid", nullable = false, length = 36)),
			@AttributeOverride(name = "viewDat", column = @Column(name = "view_dat", nullable = false, length = 35)) })
	public UserViewResultLogId getId() {
		return this.id;
	}

	public void setId(UserViewResultLogId id) {
		this.id = id;
	}

	@Column(name = "dept_id", length = 36)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "user_ip", length = 128)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
