package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-30 16:21:58 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VBillMessage generated by hbm2java
 */
@Entity
@Table(name = "v_bill_message", schema = "public")
public class VBillMessage implements java.io.Serializable {

	private VBillMessageId id;

	public VBillMessage() {
	}

	public VBillMessage(VBillMessageId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "billUuid", column = @Column(name = "bill_uuid", length = 36)),
			@AttributeOverride(name = "createMessageUserId", column = @Column(name = "create_message_user_id", length = 36)),
			@AttributeOverride(name = "messageType", column = @Column(name = "message_type", length = 4)),
			@AttributeOverride(name = "createDat", column = @Column(name = "create_dat", length = 35)),
			@AttributeOverride(name = "messageUuid", column = @Column(name = "message_uuid", length = 36)),
			@AttributeOverride(name = "ipAddr", column = @Column(name = "ip_addr", length = 64)),
			@AttributeOverride(name = "deptId", column = @Column(name = "dept_id", length = 36)),
			@AttributeOverride(name = "message", column = @Column(name = "message", length = 1024)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 45)),
			@AttributeOverride(name = "deptName", column = @Column(name = "dept_name", length = 128)),
			@AttributeOverride(name = "messageTypeName", column = @Column(name = "message_type_name", length = 90)) })
	public VBillMessageId getId() {
		return this.id;
	}

	public void setId(VBillMessageId id) {
		this.id = id;
	}

}
