package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-2 15:03:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VBillMessageId generated by hbm2java
 */
@Embeddable
public class VBillMessageId implements java.io.Serializable {

	private String billUuid;
	private String createMessageUserId;
	private String messageType;
	private Date createDat;
	private String messageUuid;
	private String ipAddr;
	private String deptId;
	private String message;
	private String userName;
	private String deptName;
	private String messageTypeName;

	public VBillMessageId() {
	}

	public VBillMessageId(String billUuid, String createMessageUserId, String messageType, Date createDat,
			String messageUuid, String ipAddr, String deptId, String message, String userName, String deptName,
			String messageTypeName) {
		this.billUuid = billUuid;
		this.createMessageUserId = createMessageUserId;
		this.messageType = messageType;
		this.createDat = createDat;
		this.messageUuid = messageUuid;
		this.ipAddr = ipAddr;
		this.deptId = deptId;
		this.message = message;
		this.userName = userName;
		this.deptName = deptName;
		this.messageTypeName = messageTypeName;
	}

	@Column(name = "bill_uuid", length = 36)
	public String getBillUuid() {
		return this.billUuid;
	}

	public void setBillUuid(String billUuid) {
		this.billUuid = billUuid;
	}

	@Column(name = "create_message_user_id", length = 36)
	public String getCreateMessageUserId() {
		return this.createMessageUserId;
	}

	public void setCreateMessageUserId(String createMessageUserId) {
		this.createMessageUserId = createMessageUserId;
	}

	@Column(name = "message_type", length = 4)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "create_dat", length = 35)
	public Date getCreateDat() {
		return this.createDat;
	}

	public void setCreateDat(Date createDat) {
		this.createDat = createDat;
	}

	@Column(name = "message_uuid", length = 36)
	public String getMessageUuid() {
		return this.messageUuid;
	}

	public void setMessageUuid(String messageUuid) {
		this.messageUuid = messageUuid;
	}

	@Column(name = "ip_addr", length = 64)
	public String getIpAddr() {
		return this.ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	@Column(name = "dept_id", length = 36)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "message", length = 1024)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "dept_name", length = 128)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "message_type_name", length = 90)
	public String getMessageTypeName() {
		return this.messageTypeName;
	}

	public void setMessageTypeName(String messageTypeName) {
		this.messageTypeName = messageTypeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VBillMessageId))
			return false;
		VBillMessageId castOther = (VBillMessageId) other;

		return ((this.getBillUuid() == castOther.getBillUuid()) || (this.getBillUuid() != null
				&& castOther.getBillUuid() != null && this.getBillUuid().equals(castOther.getBillUuid())))
				&& ((this.getCreateMessageUserId() == castOther.getCreateMessageUserId())
						|| (this.getCreateMessageUserId() != null && castOther.getCreateMessageUserId() != null
								&& this.getCreateMessageUserId().equals(castOther.getCreateMessageUserId())))
				&& ((this.getMessageType() == castOther.getMessageType())
						|| (this.getMessageType() != null && castOther.getMessageType() != null
								&& this.getMessageType().equals(castOther.getMessageType())))
				&& ((this.getCreateDat() == castOther.getCreateDat()) || (this.getCreateDat() != null
						&& castOther.getCreateDat() != null && this.getCreateDat().equals(castOther.getCreateDat())))
				&& ((this.getMessageUuid() == castOther.getMessageUuid())
						|| (this.getMessageUuid() != null && castOther.getMessageUuid() != null
								&& this.getMessageUuid().equals(castOther.getMessageUuid())))
				&& ((this.getIpAddr() == castOther.getIpAddr()) || (this.getIpAddr() != null
						&& castOther.getIpAddr() != null && this.getIpAddr().equals(castOther.getIpAddr())))
				&& ((this.getDeptId() == castOther.getDeptId()) || (this.getDeptId() != null
						&& castOther.getDeptId() != null && this.getDeptId().equals(castOther.getDeptId())))
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getDeptName() == castOther.getDeptName()) || (this.getDeptName() != null
						&& castOther.getDeptName() != null && this.getDeptName().equals(castOther.getDeptName())))
				&& ((this.getMessageTypeName() == castOther.getMessageTypeName())
						|| (this.getMessageTypeName() != null && castOther.getMessageTypeName() != null
								&& this.getMessageTypeName().equals(castOther.getMessageTypeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBillUuid() == null ? 0 : this.getBillUuid().hashCode());
		result = 37 * result + (getCreateMessageUserId() == null ? 0 : this.getCreateMessageUserId().hashCode());
		result = 37 * result + (getMessageType() == null ? 0 : this.getMessageType().hashCode());
		result = 37 * result + (getCreateDat() == null ? 0 : this.getCreateDat().hashCode());
		result = 37 * result + (getMessageUuid() == null ? 0 : this.getMessageUuid().hashCode());
		result = 37 * result + (getIpAddr() == null ? 0 : this.getIpAddr().hashCode());
		result = 37 * result + (getDeptId() == null ? 0 : this.getDeptId().hashCode());
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getDeptName() == null ? 0 : this.getDeptName().hashCode());
		result = 37 * result + (getMessageTypeName() == null ? 0 : this.getMessageTypeName().hashCode());
		return result;
	}

}
