package gov.cqaudit.finance.hibernate.entities;
// Generated 2017-12-28 13:03:11 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VBillDBackId generated by hbm2java
 */
@Embeddable
public class VBillDBackId implements java.io.Serializable {

	private String billUuid;
	private String detailUuid;
	private String bankCode;
	private String businessCode;
	private String searchParCode;
	private String searchParValue;
	private Boolean effective;
	private Date unEffectiveDat;
	private String unEffectiveUserid;
	private String createUserid;
	private Date createDat;
	private String accountId;
	private BigDecimal detailCount;

	public VBillDBackId() {
	}

	public VBillDBackId(String billUuid, String detailUuid, String bankCode, String businessCode, String searchParCode,
			String searchParValue, Boolean effective, Date unEffectiveDat, String unEffectiveUserid,
			String createUserid, Date createDat, String accountId, BigDecimal detailCount) {
		this.billUuid = billUuid;
		this.detailUuid = detailUuid;
		this.bankCode = bankCode;
		this.businessCode = businessCode;
		this.searchParCode = searchParCode;
		this.searchParValue = searchParValue;
		this.effective = effective;
		this.unEffectiveDat = unEffectiveDat;
		this.unEffectiveUserid = unEffectiveUserid;
		this.createUserid = createUserid;
		this.createDat = createDat;
		this.accountId = accountId;
		this.detailCount = detailCount;
	}

	@Column(name = "bill_uuid", length = 36)
	public String getBillUuid() {
		return this.billUuid;
	}

	public void setBillUuid(String billUuid) {
		this.billUuid = billUuid;
	}

	@Column(name = "detail_uuid", length = 36)
	public String getDetailUuid() {
		return this.detailUuid;
	}

	public void setDetailUuid(String detailUuid) {
		this.detailUuid = detailUuid;
	}

	@Column(name = "bank_code", length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "business_code", length = 4)
	public String getBusinessCode() {
		return this.businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}

	@Column(name = "search_par_code", length = 4)
	public String getSearchParCode() {
		return this.searchParCode;
	}

	public void setSearchParCode(String searchParCode) {
		this.searchParCode = searchParCode;
	}

	@Column(name = "search_par_value", length = 1024)
	public String getSearchParValue() {
		return this.searchParValue;
	}

	public void setSearchParValue(String searchParValue) {
		this.searchParValue = searchParValue;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	@Column(name = "un_effective_dat", length = 35)
	public Date getUnEffectiveDat() {
		return this.unEffectiveDat;
	}

	public void setUnEffectiveDat(Date unEffectiveDat) {
		this.unEffectiveDat = unEffectiveDat;
	}

	@Column(name = "un_effective_userid", length = 36)
	public String getUnEffectiveUserid() {
		return this.unEffectiveUserid;
	}

	public void setUnEffectiveUserid(String unEffectiveUserid) {
		this.unEffectiveUserid = unEffectiveUserid;
	}

	@Column(name = "create_userid", length = 36)
	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	@Column(name = "create_dat", length = 35)
	public Date getCreateDat() {
		return this.createDat;
	}

	public void setCreateDat(Date createDat) {
		this.createDat = createDat;
	}

	@Column(name = "account_id", length = 128)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "detail_count", precision = 131089, scale = 0)
	public BigDecimal getDetailCount() {
		return this.detailCount;
	}

	public void setDetailCount(BigDecimal detailCount) {
		this.detailCount = detailCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VBillDBackId))
			return false;
		VBillDBackId castOther = (VBillDBackId) other;

		return ((this.getBillUuid() == castOther.getBillUuid()) || (this.getBillUuid() != null
				&& castOther.getBillUuid() != null && this.getBillUuid().equals(castOther.getBillUuid())))
				&& ((this.getDetailUuid() == castOther.getDetailUuid()) || (this.getDetailUuid() != null
						&& castOther.getDetailUuid() != null && this.getDetailUuid().equals(castOther.getDetailUuid())))
				&& ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
						&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getBusinessCode() == castOther.getBusinessCode())
						|| (this.getBusinessCode() != null && castOther.getBusinessCode() != null
								&& this.getBusinessCode().equals(castOther.getBusinessCode())))
				&& ((this.getSearchParCode() == castOther.getSearchParCode())
						|| (this.getSearchParCode() != null && castOther.getSearchParCode() != null
								&& this.getSearchParCode().equals(castOther.getSearchParCode())))
				&& ((this.getSearchParValue() == castOther.getSearchParValue())
						|| (this.getSearchParValue() != null && castOther.getSearchParValue() != null
								&& this.getSearchParValue().equals(castOther.getSearchParValue())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())))
				&& ((this.getUnEffectiveDat() == castOther.getUnEffectiveDat())
						|| (this.getUnEffectiveDat() != null && castOther.getUnEffectiveDat() != null
								&& this.getUnEffectiveDat().equals(castOther.getUnEffectiveDat())))
				&& ((this.getUnEffectiveUserid() == castOther.getUnEffectiveUserid())
						|| (this.getUnEffectiveUserid() != null && castOther.getUnEffectiveUserid() != null
								&& this.getUnEffectiveUserid().equals(castOther.getUnEffectiveUserid())))
				&& ((this.getCreateUserid() == castOther.getCreateUserid())
						|| (this.getCreateUserid() != null && castOther.getCreateUserid() != null
								&& this.getCreateUserid().equals(castOther.getCreateUserid())))
				&& ((this.getCreateDat() == castOther.getCreateDat()) || (this.getCreateDat() != null
						&& castOther.getCreateDat() != null && this.getCreateDat().equals(castOther.getCreateDat())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this.getAccountId() != null
						&& castOther.getAccountId() != null && this.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getDetailCount() == castOther.getDetailCount())
						|| (this.getDetailCount() != null && castOther.getDetailCount() != null
								&& this.getDetailCount().equals(castOther.getDetailCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBillUuid() == null ? 0 : this.getBillUuid().hashCode());
		result = 37 * result + (getDetailUuid() == null ? 0 : this.getDetailUuid().hashCode());
		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getBusinessCode() == null ? 0 : this.getBusinessCode().hashCode());
		result = 37 * result + (getSearchParCode() == null ? 0 : this.getSearchParCode().hashCode());
		result = 37 * result + (getSearchParValue() == null ? 0 : this.getSearchParValue().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		result = 37 * result + (getUnEffectiveDat() == null ? 0 : this.getUnEffectiveDat().hashCode());
		result = 37 * result + (getUnEffectiveUserid() == null ? 0 : this.getUnEffectiveUserid().hashCode());
		result = 37 * result + (getCreateUserid() == null ? 0 : this.getCreateUserid().hashCode());
		result = 37 * result + (getCreateDat() == null ? 0 : this.getCreateDat().hashCode());
		result = 37 * result + (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result + (getDetailCount() == null ? 0 : this.getDetailCount().hashCode());
		return result;
	}

}
