package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-5 2:10:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VBusinessSearchPar generated by hbm2java
 */
@Entity
@Table(name = "v_business_search_par", schema = "public")
public class VBusinessSearchPar implements java.io.Serializable {

	private VBusinessSearchParId id;

	public VBusinessSearchPar() {
	}

	public VBusinessSearchPar(VBusinessSearchParId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "businessCode", column = @Column(name = "business_code", length = 4)),
			@AttributeOverride(name = "searchParCode", column = @Column(name = "search_par_code", length = 4)),
			@AttributeOverride(name = "SId", column = @Column(name = "s_id", length = 45)),
			@AttributeOverride(name = "SDesc", column = @Column(name = "s_desc", length = 45)),
			@AttributeOverride(name = "SCode", column = @Column(name = "s_code", length = 45)),
			@AttributeOverride(name = "SValue", column = @Column(name = "s_value", length = 90)) })
	public VBusinessSearchParId getId() {
		return this.id;
	}

	public void setId(VBusinessSearchParId id) {
		this.id = id;
	}

}
