package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-2 15:03:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VDataCorePrivateAccountInfoId generated by hbm2java
 */
@Embeddable
public class VDataCorePrivateAccountInfoId implements java.io.Serializable {

	private String privateAccountId;
	private Date timepoint;
	private String privateAccountName;
	private String privateCustomId;
	private String privateCardNo;
	private String bankCode;
	private Date privateOpenDat;
	private Date privateCloseDat;
	private String privateAcountStatus;

	public VDataCorePrivateAccountInfoId() {
	}

	public VDataCorePrivateAccountInfoId(String privateAccountId, Date timepoint, String privateAccountName,
			String privateCustomId, String privateCardNo, String bankCode, Date privateOpenDat, Date privateCloseDat,
			String privateAcountStatus) {
		this.privateAccountId = privateAccountId;
		this.timepoint = timepoint;
		this.privateAccountName = privateAccountName;
		this.privateCustomId = privateCustomId;
		this.privateCardNo = privateCardNo;
		this.bankCode = bankCode;
		this.privateOpenDat = privateOpenDat;
		this.privateCloseDat = privateCloseDat;
		this.privateAcountStatus = privateAcountStatus;
	}

	@Column(name = "private_account_id", length = 128)
	public String getPrivateAccountId() {
		return this.privateAccountId;
	}

	public void setPrivateAccountId(String privateAccountId) {
		this.privateAccountId = privateAccountId;
	}

	@Column(name = "timepoint", length = 35)
	public Date getTimepoint() {
		return this.timepoint;
	}

	public void setTimepoint(Date timepoint) {
		this.timepoint = timepoint;
	}

	@Column(name = "private_account_name", length = 256)
	public String getPrivateAccountName() {
		return this.privateAccountName;
	}

	public void setPrivateAccountName(String privateAccountName) {
		this.privateAccountName = privateAccountName;
	}

	@Column(name = "private_custom_id", length = 128)
	public String getPrivateCustomId() {
		return this.privateCustomId;
	}

	public void setPrivateCustomId(String privateCustomId) {
		this.privateCustomId = privateCustomId;
	}

	@Column(name = "private_card_no", length = 64)
	public String getPrivateCardNo() {
		return this.privateCardNo;
	}

	public void setPrivateCardNo(String privateCardNo) {
		this.privateCardNo = privateCardNo;
	}

	@Column(name = "bank_code", length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "private_open_dat", length = 35)
	public Date getPrivateOpenDat() {
		return this.privateOpenDat;
	}

	public void setPrivateOpenDat(Date privateOpenDat) {
		this.privateOpenDat = privateOpenDat;
	}

	@Column(name = "private_close_dat", length = 35)
	public Date getPrivateCloseDat() {
		return this.privateCloseDat;
	}

	public void setPrivateCloseDat(Date privateCloseDat) {
		this.privateCloseDat = privateCloseDat;
	}

	@Column(name = "private_acount_status", length = 32)
	public String getPrivateAcountStatus() {
		return this.privateAcountStatus;
	}

	public void setPrivateAcountStatus(String privateAcountStatus) {
		this.privateAcountStatus = privateAcountStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VDataCorePrivateAccountInfoId))
			return false;
		VDataCorePrivateAccountInfoId castOther = (VDataCorePrivateAccountInfoId) other;

		return ((this.getPrivateAccountId() == castOther.getPrivateAccountId())
				|| (this.getPrivateAccountId() != null && castOther.getPrivateAccountId() != null
						&& this.getPrivateAccountId().equals(castOther.getPrivateAccountId())))
				&& ((this.getTimepoint() == castOther.getTimepoint()) || (this.getTimepoint() != null
						&& castOther.getTimepoint() != null && this.getTimepoint().equals(castOther.getTimepoint())))
				&& ((this.getPrivateAccountName() == castOther.getPrivateAccountName())
						|| (this.getPrivateAccountName() != null && castOther.getPrivateAccountName() != null
								&& this.getPrivateAccountName().equals(castOther.getPrivateAccountName())))
				&& ((this.getPrivateCustomId() == castOther.getPrivateCustomId())
						|| (this.getPrivateCustomId() != null && castOther.getPrivateCustomId() != null
								&& this.getPrivateCustomId().equals(castOther.getPrivateCustomId())))
				&& ((this.getPrivateCardNo() == castOther.getPrivateCardNo())
						|| (this.getPrivateCardNo() != null && castOther.getPrivateCardNo() != null
								&& this.getPrivateCardNo().equals(castOther.getPrivateCardNo())))
				&& ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
						&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getPrivateOpenDat() == castOther.getPrivateOpenDat())
						|| (this.getPrivateOpenDat() != null && castOther.getPrivateOpenDat() != null
								&& this.getPrivateOpenDat().equals(castOther.getPrivateOpenDat())))
				&& ((this.getPrivateCloseDat() == castOther.getPrivateCloseDat())
						|| (this.getPrivateCloseDat() != null && castOther.getPrivateCloseDat() != null
								&& this.getPrivateCloseDat().equals(castOther.getPrivateCloseDat())))
				&& ((this.getPrivateAcountStatus() == castOther.getPrivateAcountStatus())
						|| (this.getPrivateAcountStatus() != null && castOther.getPrivateAcountStatus() != null
								&& this.getPrivateAcountStatus().equals(castOther.getPrivateAcountStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPrivateAccountId() == null ? 0 : this.getPrivateAccountId().hashCode());
		result = 37 * result + (getTimepoint() == null ? 0 : this.getTimepoint().hashCode());
		result = 37 * result + (getPrivateAccountName() == null ? 0 : this.getPrivateAccountName().hashCode());
		result = 37 * result + (getPrivateCustomId() == null ? 0 : this.getPrivateCustomId().hashCode());
		result = 37 * result + (getPrivateCardNo() == null ? 0 : this.getPrivateCardNo().hashCode());
		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getPrivateOpenDat() == null ? 0 : this.getPrivateOpenDat().hashCode());
		result = 37 * result + (getPrivateCloseDat() == null ? 0 : this.getPrivateCloseDat().hashCode());
		result = 37 * result + (getPrivateAcountStatus() == null ? 0 : this.getPrivateAcountStatus().hashCode());
		return result;
	}

}
