package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-3 12:12:28 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDataTransBack generated by hbm2java
 */
@Entity
@Table(name = "v_data_trans_back", schema = "public")
public class VDataTransBack implements java.io.Serializable {

	private VDataTransBackId id;

	public VDataTransBack() {
	}

	public VDataTransBack(VDataTransBackId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "transUuid", column = @Column(name = "trans_uuid", length = 36)),
			@AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", length = 4)),
			@AttributeOverride(name = "tableCode", column = @Column(name = "table_code", length = 4)),
			@AttributeOverride(name = "rowsCount", column = @Column(name = "rows_count", precision = 131089, scale = 0)) })
	public VDataTransBackId getId() {
		return this.id;
	}

	public void setId(VDataTransBackId id) {
		this.id = id;
	}

}
