package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-5 1:05:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDataCorePublicAccountInfo generated by hbm2java
 */
@Entity
@Table(name = "v_data_core_public_account_info", schema = "public")
public class VDataCorePublicAccountInfo implements java.io.Serializable {

	private VDataCorePublicAccountInfoId id;

	public VDataCorePublicAccountInfo() {
	}

	public VDataCorePublicAccountInfo(VDataCorePublicAccountInfoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", length = 4)),
			@AttributeOverride(name = "publicAccountId", column = @Column(name = "public_account_id", length = 128)),
			@AttributeOverride(name = "publicAccountName", column = @Column(name = "public_account_name", length = 256)),
			@AttributeOverride(name = "publicAccountStatus", column = @Column(name = "public_account_status", length = 32)),
			@AttributeOverride(name = "publicOpenDat", column = @Column(name = "public_open_dat", length = 35)),
			@AttributeOverride(name = "publicCloseDat", column = @Column(name = "public_close_dat", length = 35)),
			@AttributeOverride(name = "publicCustomId", column = @Column(name = "public_custom_id", length = 128)) })
	public VDataCorePublicAccountInfoId getId() {
		return this.id;
	}

	public void setId(VDataCorePublicAccountInfoId id) {
		this.id = id;
	}

}
