package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-2 21:10:43 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VDataCorePublicAccountTradeDetailId generated by hbm2java
 */
@Embeddable
public class VDataCorePublicAccountTradeDetailId implements java.io.Serializable {

	private String bankCode;
	private String publicAccountId;
	private String publicTradeSeq;
	private BigDecimal publicAmount;
	private String publicOpAccountId;
	private String publicOpBankId;
	private String publicOpBankName;
	private String publicOpAccountName;
	private String publicTradeCode;
	private String publicTradeName;
	private Date publicTradeDat;
	private BigDecimal publicBalance;
	private String publicBankOrgId;
	private String publicBankOrgName;
	private String publicRemark;
	private String publicAccountName;

	public VDataCorePublicAccountTradeDetailId() {
	}

	public VDataCorePublicAccountTradeDetailId(String bankCode, String publicAccountId, String publicTradeSeq,
			BigDecimal publicAmount, String publicOpAccountId, String publicOpBankId, String publicOpBankName,
			String publicOpAccountName, String publicTradeCode, String publicTradeName, Date publicTradeDat,
			BigDecimal publicBalance, String publicBankOrgId, String publicBankOrgName, String publicRemark,
			String publicAccountName) {
		this.bankCode = bankCode;
		this.publicAccountId = publicAccountId;
		this.publicTradeSeq = publicTradeSeq;
		this.publicAmount = publicAmount;
		this.publicOpAccountId = publicOpAccountId;
		this.publicOpBankId = publicOpBankId;
		this.publicOpBankName = publicOpBankName;
		this.publicOpAccountName = publicOpAccountName;
		this.publicTradeCode = publicTradeCode;
		this.publicTradeName = publicTradeName;
		this.publicTradeDat = publicTradeDat;
		this.publicBalance = publicBalance;
		this.publicBankOrgId = publicBankOrgId;
		this.publicBankOrgName = publicBankOrgName;
		this.publicRemark = publicRemark;
		this.publicAccountName = publicAccountName;
	}

	@Column(name = "bank_code", length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "public_account_id", length = 128)
	public String getPublicAccountId() {
		return this.publicAccountId;
	}

	public void setPublicAccountId(String publicAccountId) {
		this.publicAccountId = publicAccountId;
	}

	@Column(name = "public_trade_seq", length = 128)
	public String getPublicTradeSeq() {
		return this.publicTradeSeq;
	}

	public void setPublicTradeSeq(String publicTradeSeq) {
		this.publicTradeSeq = publicTradeSeq;
	}

	@Column(name = "public_amount", precision = 131089, scale = 0)
	public BigDecimal getPublicAmount() {
		return this.publicAmount;
	}

	public void setPublicAmount(BigDecimal publicAmount) {
		this.publicAmount = publicAmount;
	}

	@Column(name = "public_op_account_id", length = 128)
	public String getPublicOpAccountId() {
		return this.publicOpAccountId;
	}

	public void setPublicOpAccountId(String publicOpAccountId) {
		this.publicOpAccountId = publicOpAccountId;
	}

	@Column(name = "public_op_bank_id", length = 128)
	public String getPublicOpBankId() {
		return this.publicOpBankId;
	}

	public void setPublicOpBankId(String publicOpBankId) {
		this.publicOpBankId = publicOpBankId;
	}

	@Column(name = "public_op_bank_name", length = 256)
	public String getPublicOpBankName() {
		return this.publicOpBankName;
	}

	public void setPublicOpBankName(String publicOpBankName) {
		this.publicOpBankName = publicOpBankName;
	}

	@Column(name = "public_op_account_name", length = 256)
	public String getPublicOpAccountName() {
		return this.publicOpAccountName;
	}

	public void setPublicOpAccountName(String publicOpAccountName) {
		this.publicOpAccountName = publicOpAccountName;
	}

	@Column(name = "public_trade_code", length = 128)
	public String getPublicTradeCode() {
		return this.publicTradeCode;
	}

	public void setPublicTradeCode(String publicTradeCode) {
		this.publicTradeCode = publicTradeCode;
	}

	@Column(name = "public_trade_name", length = 256)
	public String getPublicTradeName() {
		return this.publicTradeName;
	}

	public void setPublicTradeName(String publicTradeName) {
		this.publicTradeName = publicTradeName;
	}

	@Column(name = "public_trade_dat", length = 35)
	public Date getPublicTradeDat() {
		return this.publicTradeDat;
	}

	public void setPublicTradeDat(Date publicTradeDat) {
		this.publicTradeDat = publicTradeDat;
	}

	@Column(name = "public_balance", precision = 131089, scale = 0)
	public BigDecimal getPublicBalance() {
		return this.publicBalance;
	}

	public void setPublicBalance(BigDecimal publicBalance) {
		this.publicBalance = publicBalance;
	}

	@Column(name = "public_bank_org_id", length = 64)
	public String getPublicBankOrgId() {
		return this.publicBankOrgId;
	}

	public void setPublicBankOrgId(String publicBankOrgId) {
		this.publicBankOrgId = publicBankOrgId;
	}

	@Column(name = "public_bank_org_name", length = 128)
	public String getPublicBankOrgName() {
		return this.publicBankOrgName;
	}

	public void setPublicBankOrgName(String publicBankOrgName) {
		this.publicBankOrgName = publicBankOrgName;
	}

	@Column(name = "public_remark", length = 2048)
	public String getPublicRemark() {
		return this.publicRemark;
	}

	public void setPublicRemark(String publicRemark) {
		this.publicRemark = publicRemark;
	}

	@Column(name = "public_account_name", length = 256)
	public String getPublicAccountName() {
		return this.publicAccountName;
	}

	public void setPublicAccountName(String publicAccountName) {
		this.publicAccountName = publicAccountName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VDataCorePublicAccountTradeDetailId))
			return false;
		VDataCorePublicAccountTradeDetailId castOther = (VDataCorePublicAccountTradeDetailId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getPublicAccountId() == castOther.getPublicAccountId())
						|| (this.getPublicAccountId() != null && castOther.getPublicAccountId() != null
								&& this.getPublicAccountId().equals(castOther.getPublicAccountId())))
				&& ((this.getPublicTradeSeq() == castOther.getPublicTradeSeq())
						|| (this.getPublicTradeSeq() != null && castOther.getPublicTradeSeq() != null
								&& this.getPublicTradeSeq().equals(castOther.getPublicTradeSeq())))
				&& ((this.getPublicAmount() == castOther.getPublicAmount())
						|| (this.getPublicAmount() != null && castOther.getPublicAmount() != null
								&& this.getPublicAmount().equals(castOther.getPublicAmount())))
				&& ((this.getPublicOpAccountId() == castOther.getPublicOpAccountId())
						|| (this.getPublicOpAccountId() != null && castOther.getPublicOpAccountId() != null
								&& this.getPublicOpAccountId().equals(castOther.getPublicOpAccountId())))
				&& ((this.getPublicOpBankId() == castOther.getPublicOpBankId())
						|| (this.getPublicOpBankId() != null && castOther.getPublicOpBankId() != null
								&& this.getPublicOpBankId().equals(castOther.getPublicOpBankId())))
				&& ((this.getPublicOpBankName() == castOther.getPublicOpBankName())
						|| (this.getPublicOpBankName() != null && castOther.getPublicOpBankName() != null
								&& this.getPublicOpBankName().equals(castOther.getPublicOpBankName())))
				&& ((this.getPublicOpAccountName() == castOther.getPublicOpAccountName())
						|| (this.getPublicOpAccountName() != null && castOther.getPublicOpAccountName() != null
								&& this.getPublicOpAccountName().equals(castOther.getPublicOpAccountName())))
				&& ((this.getPublicTradeCode() == castOther.getPublicTradeCode())
						|| (this.getPublicTradeCode() != null && castOther.getPublicTradeCode() != null
								&& this.getPublicTradeCode().equals(castOther.getPublicTradeCode())))
				&& ((this.getPublicTradeName() == castOther.getPublicTradeName())
						|| (this.getPublicTradeName() != null && castOther.getPublicTradeName() != null
								&& this.getPublicTradeName().equals(castOther.getPublicTradeName())))
				&& ((this.getPublicTradeDat() == castOther.getPublicTradeDat())
						|| (this.getPublicTradeDat() != null && castOther.getPublicTradeDat() != null
								&& this.getPublicTradeDat().equals(castOther.getPublicTradeDat())))
				&& ((this.getPublicBalance() == castOther.getPublicBalance())
						|| (this.getPublicBalance() != null && castOther.getPublicBalance() != null
								&& this.getPublicBalance().equals(castOther.getPublicBalance())))
				&& ((this.getPublicBankOrgId() == castOther.getPublicBankOrgId())
						|| (this.getPublicBankOrgId() != null && castOther.getPublicBankOrgId() != null
								&& this.getPublicBankOrgId().equals(castOther.getPublicBankOrgId())))
				&& ((this.getPublicBankOrgName() == castOther.getPublicBankOrgName())
						|| (this.getPublicBankOrgName() != null && castOther.getPublicBankOrgName() != null
								&& this.getPublicBankOrgName().equals(castOther.getPublicBankOrgName())))
				&& ((this.getPublicRemark() == castOther.getPublicRemark())
						|| (this.getPublicRemark() != null && castOther.getPublicRemark() != null
								&& this.getPublicRemark().equals(castOther.getPublicRemark())))
				&& ((this.getPublicAccountName() == castOther.getPublicAccountName())
						|| (this.getPublicAccountName() != null && castOther.getPublicAccountName() != null
								&& this.getPublicAccountName().equals(castOther.getPublicAccountName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getPublicAccountId() == null ? 0 : this.getPublicAccountId().hashCode());
		result = 37 * result + (getPublicTradeSeq() == null ? 0 : this.getPublicTradeSeq().hashCode());
		result = 37 * result + (getPublicAmount() == null ? 0 : this.getPublicAmount().hashCode());
		result = 37 * result + (getPublicOpAccountId() == null ? 0 : this.getPublicOpAccountId().hashCode());
		result = 37 * result + (getPublicOpBankId() == null ? 0 : this.getPublicOpBankId().hashCode());
		result = 37 * result + (getPublicOpBankName() == null ? 0 : this.getPublicOpBankName().hashCode());
		result = 37 * result + (getPublicOpAccountName() == null ? 0 : this.getPublicOpAccountName().hashCode());
		result = 37 * result + (getPublicTradeCode() == null ? 0 : this.getPublicTradeCode().hashCode());
		result = 37 * result + (getPublicTradeName() == null ? 0 : this.getPublicTradeName().hashCode());
		result = 37 * result + (getPublicTradeDat() == null ? 0 : this.getPublicTradeDat().hashCode());
		result = 37 * result + (getPublicBalance() == null ? 0 : this.getPublicBalance().hashCode());
		result = 37 * result + (getPublicBankOrgId() == null ? 0 : this.getPublicBankOrgId().hashCode());
		result = 37 * result + (getPublicBankOrgName() == null ? 0 : this.getPublicBankOrgName().hashCode());
		result = 37 * result + (getPublicRemark() == null ? 0 : this.getPublicRemark().hashCode());
		result = 37 * result + (getPublicAccountName() == null ? 0 : this.getPublicAccountName().hashCode());
		return result;
	}

}
