package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-2 21:10:43 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VDataCorePrivateCustomBaseId generated by hbm2java
 */
@Embeddable
public class VDataCorePrivateCustomBaseId implements java.io.Serializable {

	private String bankCode;
	private String privateCustomId;
	private String privateCustomName;
	private String privateCompany;
	private String privatePostAddress;
	private String privateWorkAddress;
	private String privateIdCard;

	public VDataCorePrivateCustomBaseId() {
	}

	public VDataCorePrivateCustomBaseId(String bankCode, String privateCustomId, String privateCustomName,
			String privateCompany, String privatePostAddress, String privateWorkAddress, String privateIdCard) {
		this.bankCode = bankCode;
		this.privateCustomId = privateCustomId;
		this.privateCustomName = privateCustomName;
		this.privateCompany = privateCompany;
		this.privatePostAddress = privatePostAddress;
		this.privateWorkAddress = privateWorkAddress;
		this.privateIdCard = privateIdCard;
	}

	@Column(name = "bank_code", length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "private_custom_id", length = 128)
	public String getPrivateCustomId() {
		return this.privateCustomId;
	}

	public void setPrivateCustomId(String privateCustomId) {
		this.privateCustomId = privateCustomId;
	}

	@Column(name = "private_custom_name", length = 256)
	public String getPrivateCustomName() {
		return this.privateCustomName;
	}

	public void setPrivateCustomName(String privateCustomName) {
		this.privateCustomName = privateCustomName;
	}

	@Column(name = "private_company", length = 256)
	public String getPrivateCompany() {
		return this.privateCompany;
	}

	public void setPrivateCompany(String privateCompany) {
		this.privateCompany = privateCompany;
	}

	@Column(name = "private_post_address", length = 512)
	public String getPrivatePostAddress() {
		return this.privatePostAddress;
	}

	public void setPrivatePostAddress(String privatePostAddress) {
		this.privatePostAddress = privatePostAddress;
	}

	@Column(name = "private_work_address", length = 512)
	public String getPrivateWorkAddress() {
		return this.privateWorkAddress;
	}

	public void setPrivateWorkAddress(String privateWorkAddress) {
		this.privateWorkAddress = privateWorkAddress;
	}

	@Column(name = "private_id_card", length = 64)
	public String getPrivateIdCard() {
		return this.privateIdCard;
	}

	public void setPrivateIdCard(String privateIdCard) {
		this.privateIdCard = privateIdCard;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VDataCorePrivateCustomBaseId))
			return false;
		VDataCorePrivateCustomBaseId castOther = (VDataCorePrivateCustomBaseId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getPrivateCustomId() == castOther.getPrivateCustomId())
						|| (this.getPrivateCustomId() != null && castOther.getPrivateCustomId() != null
								&& this.getPrivateCustomId().equals(castOther.getPrivateCustomId())))
				&& ((this.getPrivateCustomName() == castOther.getPrivateCustomName())
						|| (this.getPrivateCustomName() != null && castOther.getPrivateCustomName() != null
								&& this.getPrivateCustomName().equals(castOther.getPrivateCustomName())))
				&& ((this.getPrivateCompany() == castOther.getPrivateCompany())
						|| (this.getPrivateCompany() != null && castOther.getPrivateCompany() != null
								&& this.getPrivateCompany().equals(castOther.getPrivateCompany())))
				&& ((this.getPrivatePostAddress() == castOther.getPrivatePostAddress())
						|| (this.getPrivatePostAddress() != null && castOther.getPrivatePostAddress() != null
								&& this.getPrivatePostAddress().equals(castOther.getPrivatePostAddress())))
				&& ((this.getPrivateWorkAddress() == castOther.getPrivateWorkAddress())
						|| (this.getPrivateWorkAddress() != null && castOther.getPrivateWorkAddress() != null
								&& this.getPrivateWorkAddress().equals(castOther.getPrivateWorkAddress())))
				&& ((this.getPrivateIdCard() == castOther.getPrivateIdCard())
						|| (this.getPrivateIdCard() != null && castOther.getPrivateIdCard() != null
								&& this.getPrivateIdCard().equals(castOther.getPrivateIdCard())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getPrivateCustomId() == null ? 0 : this.getPrivateCustomId().hashCode());
		result = 37 * result + (getPrivateCustomName() == null ? 0 : this.getPrivateCustomName().hashCode());
		result = 37 * result + (getPrivateCompany() == null ? 0 : this.getPrivateCompany().hashCode());
		result = 37 * result + (getPrivatePostAddress() == null ? 0 : this.getPrivatePostAddress().hashCode());
		result = 37 * result + (getPrivateWorkAddress() == null ? 0 : this.getPrivateWorkAddress().hashCode());
		result = 37 * result + (getPrivateIdCard() == null ? 0 : this.getPrivateIdCard().hashCode());
		return result;
	}

}
