package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-2 21:10:43 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDataCorePrivateCustomBase generated by hbm2java
 */
@Entity
@Table(name = "v_data_core_private_custom_base", schema = "public")
public class VDataCorePrivateCustomBase implements java.io.Serializable {

	private VDataCorePrivateCustomBaseId id;

	public VDataCorePrivateCustomBase() {
	}

	public VDataCorePrivateCustomBase(VDataCorePrivateCustomBaseId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", length = 4)),
			@AttributeOverride(name = "privateCustomId", column = @Column(name = "private_custom_id", length = 128)),
			@AttributeOverride(name = "privateCustomName", column = @Column(name = "private_custom_name", length = 256)),
			@AttributeOverride(name = "privateCompany", column = @Column(name = "private_company", length = 256)),
			@AttributeOverride(name = "privatePostAddress", column = @Column(name = "private_post_address", length = 512)),
			@AttributeOverride(name = "privateWorkAddress", column = @Column(name = "private_work_address", length = 512)),
			@AttributeOverride(name = "privateIdCard", column = @Column(name = "private_id_card", length = 64)) })
	public VDataCorePrivateCustomBaseId getId() {
		return this.id;
	}

	public void setId(VDataCorePrivateCustomBaseId id) {
		this.id = id;
	}

}
