package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-2 15:03:25 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDataCorePublicAccountTradeDetail generated by hbm2java
 */
@Entity
@Table(name = "v_data_core_public_account_trade_detail", schema = "public")
public class VDataCorePublicAccountTradeDetail implements java.io.Serializable {

	private VDataCorePublicAccountTradeDetailId id;

	public VDataCorePublicAccountTradeDetail() {
	}

	public VDataCorePublicAccountTradeDetail(VDataCorePublicAccountTradeDetailId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", length = 4)),
			@AttributeOverride(name = "publicAccountId", column = @Column(name = "public_account_id", length = 128)),
			@AttributeOverride(name = "publicTradeSeq", column = @Column(name = "public_trade_seq", length = 128)),
			@AttributeOverride(name = "publicAmount", column = @Column(name = "public_amount", precision = 131089, scale = 0)),
			@AttributeOverride(name = "publicOpAccountId", column = @Column(name = "public_op_account_id", length = 128)),
			@AttributeOverride(name = "publicOpBankId", column = @Column(name = "public_op_bank_id", length = 128)),
			@AttributeOverride(name = "publicOpBankName", column = @Column(name = "public_op_bank_name", length = 256)),
			@AttributeOverride(name = "publicOpAccountName", column = @Column(name = "public_op_account_name", length = 256)),
			@AttributeOverride(name = "publicTradeCode", column = @Column(name = "public_trade_code", length = 128)),
			@AttributeOverride(name = "publicTradeName", column = @Column(name = "public_trade_name", length = 256)),
			@AttributeOverride(name = "publicTradeDat", column = @Column(name = "public_trade_dat", length = 35)),
			@AttributeOverride(name = "publicBalance", column = @Column(name = "public_balance", precision = 131089, scale = 0)),
			@AttributeOverride(name = "publicBankOrgId", column = @Column(name = "public_bank_org_id", length = 64)),
			@AttributeOverride(name = "publicBankOrgName", column = @Column(name = "public_bank_org_name", length = 128)),
			@AttributeOverride(name = "publicRemark", column = @Column(name = "public_remark", length = 2048)),
			@AttributeOverride(name = "publicAccountName", column = @Column(name = "public_account_name", length = 256)) })
	public VDataCorePublicAccountTradeDetailId getId() {
		return this.id;
	}

	public void setId(VDataCorePublicAccountTradeDetailId id) {
		this.id = id;
	}

}
