package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-3 12:12:28 by Hibernate Tools 5.2.3.Final

import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPictureId generated by hbm2java
 */
@Embeddable
public class VPictureId implements java.io.Serializable {

	private String uuid;
	private Date opDat;
	private String userId;
	private String billUuid;
	private Boolean effective;
	private String fileType;
	private String fileName;
	private Long fileLength;
	private byte[] binData;
	private String userName;

	public VPictureId() {
	}

	public VPictureId(String uuid, Date opDat, String userId, String billUuid, Boolean effective, String fileType,
			String fileName, Long fileLength, byte[] binData, String userName) {
		this.uuid = uuid;
		this.opDat = opDat;
		this.userId = userId;
		this.billUuid = billUuid;
		this.effective = effective;
		this.fileType = fileType;
		this.fileName = fileName;
		this.fileLength = fileLength;
		this.binData = binData;
		this.userName = userName;
	}

	@Column(name = "uuid", length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "op_dat", length = 35)
	public Date getOpDat() {
		return this.opDat;
	}

	public void setOpDat(Date opDat) {
		this.opDat = opDat;
	}

	@Column(name = "user_id", length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "bill_uuid", length = 36)
	public String getBillUuid() {
		return this.billUuid;
	}

	public void setBillUuid(String billUuid) {
		this.billUuid = billUuid;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	@Column(name = "file_type", length = 1024)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "file_name", length = 1024)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_length")
	public Long getFileLength() {
		return this.fileLength;
	}

	public void setFileLength(Long fileLength) {
		this.fileLength = fileLength;
	}

	@Column(name = "bin_data")
	public byte[] getBinData() {
		return this.binData;
	}

	public void setBinData(byte[] binData) {
		this.binData = binData;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPictureId))
			return false;
		VPictureId castOther = (VPictureId) other;

		return ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null
				&& this.getUuid().equals(castOther.getUuid())))
				&& ((this.getOpDat() == castOther.getOpDat()) || (this.getOpDat() != null
						&& castOther.getOpDat() != null && this.getOpDat().equals(castOther.getOpDat())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getBillUuid() == castOther.getBillUuid()) || (this.getBillUuid() != null
						&& castOther.getBillUuid() != null && this.getBillUuid().equals(castOther.getBillUuid())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())))
				&& ((this.getFileType() == castOther.getFileType()) || (this.getFileType() != null
						&& castOther.getFileType() != null && this.getFileType().equals(castOther.getFileType())))
				&& ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null
						&& castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())))
				&& ((this.getFileLength() == castOther.getFileLength()) || (this.getFileLength() != null
						&& castOther.getFileLength() != null && this.getFileLength().equals(castOther.getFileLength())))
				&& ((this.getBinData() == castOther.getBinData()) || (this.getBinData() != null
						&& castOther.getBinData() != null && Arrays.equals(this.getBinData(), castOther.getBinData())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getOpDat() == null ? 0 : this.getOpDat().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getBillUuid() == null ? 0 : this.getBillUuid().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		result = 37 * result + (getFileType() == null ? 0 : this.getFileType().hashCode());
		result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result + (getFileLength() == null ? 0 : this.getFileLength().hashCode());
		result = 37 * result + (getBinData() == null ? 0 : Arrays.hashCode(this.getBinData()));
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		return result;
	}

}
