package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-3 12:12:28 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VSearchPublicCustomAccountId generated by hbm2java
 */
@Embeddable
public class VSearchPublicCustomAccountId implements java.io.Serializable {

	private String bankCode;
	private String publicAccountName;
	private String publicAccountId;
	private String publicCustomId;
	private String publicCustomName;
	private Long detailCount;

	public VSearchPublicCustomAccountId() {
	}

	public VSearchPublicCustomAccountId(String bankCode, String publicAccountName, String publicAccountId,
			String publicCustomId, String publicCustomName, Long detailCount) {
		this.bankCode = bankCode;
		this.publicAccountName = publicAccountName;
		this.publicAccountId = publicAccountId;
		this.publicCustomId = publicCustomId;
		this.publicCustomName = publicCustomName;
		this.detailCount = detailCount;
	}

	@Column(name = "bank_code", length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "public_account_name", length = 256)
	public String getPublicAccountName() {
		return this.publicAccountName;
	}

	public void setPublicAccountName(String publicAccountName) {
		this.publicAccountName = publicAccountName;
	}

	@Column(name = "public_account_id", length = 128)
	public String getPublicAccountId() {
		return this.publicAccountId;
	}

	public void setPublicAccountId(String publicAccountId) {
		this.publicAccountId = publicAccountId;
	}

	@Column(name = "public_custom_id", length = 128)
	public String getPublicCustomId() {
		return this.publicCustomId;
	}

	public void setPublicCustomId(String publicCustomId) {
		this.publicCustomId = publicCustomId;
	}

	@Column(name = "public_custom_name", length = 256)
	public String getPublicCustomName() {
		return this.publicCustomName;
	}

	public void setPublicCustomName(String publicCustomName) {
		this.publicCustomName = publicCustomName;
	}

	@Column(name = "detail_count")
	public Long getDetailCount() {
		return this.detailCount;
	}

	public void setDetailCount(Long detailCount) {
		this.detailCount = detailCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VSearchPublicCustomAccountId))
			return false;
		VSearchPublicCustomAccountId castOther = (VSearchPublicCustomAccountId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getPublicAccountName() == castOther.getPublicAccountName())
						|| (this.getPublicAccountName() != null && castOther.getPublicAccountName() != null
								&& this.getPublicAccountName().equals(castOther.getPublicAccountName())))
				&& ((this.getPublicAccountId() == castOther.getPublicAccountId())
						|| (this.getPublicAccountId() != null && castOther.getPublicAccountId() != null
								&& this.getPublicAccountId().equals(castOther.getPublicAccountId())))
				&& ((this.getPublicCustomId() == castOther.getPublicCustomId())
						|| (this.getPublicCustomId() != null && castOther.getPublicCustomId() != null
								&& this.getPublicCustomId().equals(castOther.getPublicCustomId())))
				&& ((this.getPublicCustomName() == castOther.getPublicCustomName())
						|| (this.getPublicCustomName() != null && castOther.getPublicCustomName() != null
								&& this.getPublicCustomName().equals(castOther.getPublicCustomName())))
				&& ((this.getDetailCount() == castOther.getDetailCount())
						|| (this.getDetailCount() != null && castOther.getDetailCount() != null
								&& this.getDetailCount().equals(castOther.getDetailCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getPublicAccountName() == null ? 0 : this.getPublicAccountName().hashCode());
		result = 37 * result + (getPublicAccountId() == null ? 0 : this.getPublicAccountId().hashCode());
		result = 37 * result + (getPublicCustomId() == null ? 0 : this.getPublicCustomId().hashCode());
		result = 37 * result + (getPublicCustomName() == null ? 0 : this.getPublicCustomName().hashCode());
		result = 37 * result + (getDetailCount() == null ? 0 : this.getDetailCount().hashCode());
		return result;
	}

}
