package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-5 2:10:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VSearchPrivateCustomAccountId generated by hbm2java
 */
@Embeddable
public class VSearchPrivateCustomAccountId implements java.io.Serializable {

	private String bankCode;
	private String privateAccountName;
	private String privateAccountId;
	private String privateCustomId;
	private String privateIdCard;
	private Long detailCount;
	private String privateCardNo;

	public VSearchPrivateCustomAccountId() {
	}

	public VSearchPrivateCustomAccountId(String bankCode, String privateAccountName, String privateAccountId,
			String privateCustomId, String privateIdCard, Long detailCount, String privateCardNo) {
		this.bankCode = bankCode;
		this.privateAccountName = privateAccountName;
		this.privateAccountId = privateAccountId;
		this.privateCustomId = privateCustomId;
		this.privateIdCard = privateIdCard;
		this.detailCount = detailCount;
		this.privateCardNo = privateCardNo;
	}

	@Column(name = "bank_code", length = 4)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "private_account_name", length = 256)
	public String getPrivateAccountName() {
		return this.privateAccountName;
	}

	public void setPrivateAccountName(String privateAccountName) {
		this.privateAccountName = privateAccountName;
	}

	@Column(name = "private_account_id", length = 128)
	public String getPrivateAccountId() {
		return this.privateAccountId;
	}

	public void setPrivateAccountId(String privateAccountId) {
		this.privateAccountId = privateAccountId;
	}

	@Column(name = "private_custom_id", length = 128)
	public String getPrivateCustomId() {
		return this.privateCustomId;
	}

	public void setPrivateCustomId(String privateCustomId) {
		this.privateCustomId = privateCustomId;
	}

	@Column(name = "private_id_card", length = 64)
	public String getPrivateIdCard() {
		return this.privateIdCard;
	}

	public void setPrivateIdCard(String privateIdCard) {
		this.privateIdCard = privateIdCard;
	}

	@Column(name = "detail_count")
	public Long getDetailCount() {
		return this.detailCount;
	}

	public void setDetailCount(Long detailCount) {
		this.detailCount = detailCount;
	}

	@Column(name = "private_card_no", length = 64)
	public String getPrivateCardNo() {
		return this.privateCardNo;
	}

	public void setPrivateCardNo(String privateCardNo) {
		this.privateCardNo = privateCardNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VSearchPrivateCustomAccountId))
			return false;
		VSearchPrivateCustomAccountId castOther = (VSearchPrivateCustomAccountId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getPrivateAccountName() == castOther.getPrivateAccountName())
						|| (this.getPrivateAccountName() != null && castOther.getPrivateAccountName() != null
								&& this.getPrivateAccountName().equals(castOther.getPrivateAccountName())))
				&& ((this.getPrivateAccountId() == castOther.getPrivateAccountId())
						|| (this.getPrivateAccountId() != null && castOther.getPrivateAccountId() != null
								&& this.getPrivateAccountId().equals(castOther.getPrivateAccountId())))
				&& ((this.getPrivateCustomId() == castOther.getPrivateCustomId())
						|| (this.getPrivateCustomId() != null && castOther.getPrivateCustomId() != null
								&& this.getPrivateCustomId().equals(castOther.getPrivateCustomId())))
				&& ((this.getPrivateIdCard() == castOther.getPrivateIdCard())
						|| (this.getPrivateIdCard() != null && castOther.getPrivateIdCard() != null
								&& this.getPrivateIdCard().equals(castOther.getPrivateIdCard())))
				&& ((this.getDetailCount() == castOther.getDetailCount())
						|| (this.getDetailCount() != null && castOther.getDetailCount() != null
								&& this.getDetailCount().equals(castOther.getDetailCount())))
				&& ((this.getPrivateCardNo() == castOther.getPrivateCardNo())
						|| (this.getPrivateCardNo() != null && castOther.getPrivateCardNo() != null
								&& this.getPrivateCardNo().equals(castOther.getPrivateCardNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getPrivateAccountName() == null ? 0 : this.getPrivateAccountName().hashCode());
		result = 37 * result + (getPrivateAccountId() == null ? 0 : this.getPrivateAccountId().hashCode());
		result = 37 * result + (getPrivateCustomId() == null ? 0 : this.getPrivateCustomId().hashCode());
		result = 37 * result + (getPrivateIdCard() == null ? 0 : this.getPrivateIdCard().hashCode());
		result = 37 * result + (getDetailCount() == null ? 0 : this.getDetailCount().hashCode());
		result = 37 * result + (getPrivateCardNo() == null ? 0 : this.getPrivateCardNo().hashCode());
		return result;
	}

}
