package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-16 13:34:04 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VStatisticsBillsResultByType generated by hbm2java
 */
@Entity
@Table(name = "v_statistics_bills_result_by_type", schema = "public")
public class VStatisticsBillsResultByType implements java.io.Serializable {

	private VStatisticsBillsResultByTypeId id;

	public VStatisticsBillsResultByType() {
	}

	public VStatisticsBillsResultByType(VStatisticsBillsResultByTypeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "publicCount", column = @Column(name = "public_count", precision = 131089, scale = 0)),
			@AttributeOverride(name = "privateCount", column = @Column(name = "private_count", precision = 131089, scale = 0)),
			@AttributeOverride(name = "publicDetail", column = @Column(name = "public_detail", precision = 131089, scale = 0)),
			@AttributeOverride(name = "privateDetail", column = @Column(name = "private_detail", precision = 131089, scale = 0)),
			@AttributeOverride(name = "deptType", column = @Column(name = "dept_type", length = 4)),
			@AttributeOverride(name = "typeName", column = @Column(name = "type_name", length = 90)),
			@AttributeOverride(name = "deptName", column = @Column(name = "dept_name", length = 128)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 13)) })
	public VStatisticsBillsResultByTypeId getId() {
		return this.id;
	}

	public void setId(VStatisticsBillsResultByTypeId id) {
		this.id = id;
	}

}
