package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-9 12:39:57 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VStatisticsBillsResultByTypeId generated by hbm2java
 */
@Embeddable
public class VStatisticsBillsResultByTypeId implements java.io.Serializable {

	private BigDecimal publicCount;
	private BigDecimal privateCount;
	private BigDecimal publicDetail;
	private BigDecimal privateDetail;
	private String deptType;
	private String typeName;
	private String deptName;
	private Date createDate;

	public VStatisticsBillsResultByTypeId() {
	}

	public VStatisticsBillsResultByTypeId(BigDecimal publicCount, BigDecimal privateCount, BigDecimal publicDetail,
			BigDecimal privateDetail, String deptType, String typeName, String deptName, Date createDate) {
		this.publicCount = publicCount;
		this.privateCount = privateCount;
		this.publicDetail = publicDetail;
		this.privateDetail = privateDetail;
		this.deptType = deptType;
		this.typeName = typeName;
		this.deptName = deptName;
		this.createDate = createDate;
	}

	@Column(name = "public_count", precision = 131089, scale = 0)
	public BigDecimal getPublicCount() {
		return this.publicCount;
	}

	public void setPublicCount(BigDecimal publicCount) {
		this.publicCount = publicCount;
	}

	@Column(name = "private_count", precision = 131089, scale = 0)
	public BigDecimal getPrivateCount() {
		return this.privateCount;
	}

	public void setPrivateCount(BigDecimal privateCount) {
		this.privateCount = privateCount;
	}

	@Column(name = "public_detail", precision = 131089, scale = 0)
	public BigDecimal getPublicDetail() {
		return this.publicDetail;
	}

	public void setPublicDetail(BigDecimal publicDetail) {
		this.publicDetail = publicDetail;
	}

	@Column(name = "private_detail", precision = 131089, scale = 0)
	public BigDecimal getPrivateDetail() {
		return this.privateDetail;
	}

	public void setPrivateDetail(BigDecimal privateDetail) {
		this.privateDetail = privateDetail;
	}

	@Column(name = "dept_type", length = 4)
	public String getDeptType() {
		return this.deptType;
	}

	public void setDeptType(String deptType) {
		this.deptType = deptType;
	}

	@Column(name = "type_name", length = 90)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "dept_name", length = 128)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "create_date", length = 13)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VStatisticsBillsResultByTypeId))
			return false;
		VStatisticsBillsResultByTypeId castOther = (VStatisticsBillsResultByTypeId) other;

		return ((this.getPublicCount() == castOther.getPublicCount()) || (this.getPublicCount() != null
				&& castOther.getPublicCount() != null && this.getPublicCount().equals(castOther.getPublicCount())))
				&& ((this.getPrivateCount() == castOther.getPrivateCount())
						|| (this.getPrivateCount() != null && castOther.getPrivateCount() != null
								&& this.getPrivateCount().equals(castOther.getPrivateCount())))
				&& ((this.getPublicDetail() == castOther.getPublicDetail())
						|| (this.getPublicDetail() != null && castOther.getPublicDetail() != null
								&& this.getPublicDetail().equals(castOther.getPublicDetail())))
				&& ((this.getPrivateDetail() == castOther.getPrivateDetail())
						|| (this.getPrivateDetail() != null && castOther.getPrivateDetail() != null
								&& this.getPrivateDetail().equals(castOther.getPrivateDetail())))
				&& ((this.getDeptType() == castOther.getDeptType()) || (this.getDeptType() != null
						&& castOther.getDeptType() != null && this.getDeptType().equals(castOther.getDeptType())))
				&& ((this.getTypeName() == castOther.getTypeName()) || (this.getTypeName() != null
						&& castOther.getTypeName() != null && this.getTypeName().equals(castOther.getTypeName())))
				&& ((this.getDeptName() == castOther.getDeptName()) || (this.getDeptName() != null
						&& castOther.getDeptName() != null && this.getDeptName().equals(castOther.getDeptName())))
				&& ((this.getCreateDate() == castOther.getCreateDate())
						|| (this.getCreateDate() != null && castOther.getCreateDate() != null
								&& this.getCreateDate().equals(castOther.getCreateDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPublicCount() == null ? 0 : this.getPublicCount().hashCode());
		result = 37 * result + (getPrivateCount() == null ? 0 : this.getPrivateCount().hashCode());
		result = 37 * result + (getPublicDetail() == null ? 0 : this.getPublicDetail().hashCode());
		result = 37 * result + (getPrivateDetail() == null ? 0 : this.getPrivateDetail().hashCode());
		result = 37 * result + (getDeptType() == null ? 0 : this.getDeptType().hashCode());
		result = 37 * result + (getTypeName() == null ? 0 : this.getTypeName().hashCode());
		result = 37 * result + (getDeptName() == null ? 0 : this.getDeptName().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		return result;
	}

}
