package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-5 1:05:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VSysUser generated by hbm2java
 */
@Entity
@Table(name = "v_sys_user", schema = "public")
public class VSysUser implements java.io.Serializable {

	private VSysUserId id;

	public VSysUser() {
	}

	public VSysUser(VSysUserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", length = 36)),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 45)),
			@AttributeOverride(name = "createTime", column = @Column(name = "create_time", length = 35)),
			@AttributeOverride(name = "pwd", column = @Column(name = "pwd", length = 45)),
			@AttributeOverride(name = "userLogin", column = @Column(name = "user_login", length = 45)),
			@AttributeOverride(name = "tel", column = @Column(name = "tel", length = 45)),
			@AttributeOverride(name = "effective", column = @Column(name = "effective")),
			@AttributeOverride(name = "online", column = @Column(name = "online")),
			@AttributeOverride(name = "lastOnlineTime", column = @Column(name = "last_online_time", length = 35)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 521)),
			@AttributeOverride(name = "deptId", column = @Column(name = "dept_id", length = 36)),
			@AttributeOverride(name = "deptName", column = @Column(name = "dept_name", length = 128)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", length = 45)),
			@AttributeOverride(name = "roleName", column = @Column(name = "role_name", length = 45)) })
	public VSysUserId getId() {
		return this.id;
	}

	public void setId(VSysUserId id) {
		this.id = id;
	}

}
