package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-16 13:34:04 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VSysUserId generated by hbm2java
 */
@Embeddable
public class VSysUserId implements java.io.Serializable {

	private String id;
	private String name;
	private Date createTime;
	private String pwd;
	private String userLogin;
	private String tel;
	private Boolean effective;
	private Boolean online;
	private Date lastOnlineTime;
	private String email;
	private String deptId;
	private String deptName;
	private String roleId;
	private String roleName;

	public VSysUserId() {
	}

	public VSysUserId(String id, String name, Date createTime, String pwd, String userLogin, String tel,
			Boolean effective, Boolean online, Date lastOnlineTime, String email, String deptId, String deptName,
			String roleId, String roleName) {
		this.id = id;
		this.name = name;
		this.createTime = createTime;
		this.pwd = pwd;
		this.userLogin = userLogin;
		this.tel = tel;
		this.effective = effective;
		this.online = online;
		this.lastOnlineTime = lastOnlineTime;
		this.email = email;
		this.deptId = deptId;
		this.deptName = deptName;
		this.roleId = roleId;
		this.roleName = roleName;
	}

	@Column(name = "id", length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "create_time", length = 35)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "pwd", length = 45)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "user_login", length = 45)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	@Column(name = "online")
	public Boolean getOnline() {
		return this.online;
	}

	public void setOnline(Boolean online) {
		this.online = online;
	}

	@Column(name = "last_online_time", length = 35)
	public Date getLastOnlineTime() {
		return this.lastOnlineTime;
	}

	public void setLastOnlineTime(Date lastOnlineTime) {
		this.lastOnlineTime = lastOnlineTime;
	}

	@Column(name = "email", length = 521)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "dept_id", length = 36)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "dept_name", length = 128)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "role_id", length = 45)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VSysUserId))
			return false;
		VSysUserId castOther = (VSysUserId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this.getCreateTime() != null
						&& castOther.getCreateTime() != null && this.getCreateTime().equals(castOther.getCreateTime())))
				&& ((this.getPwd() == castOther.getPwd()) || (this.getPwd() != null && castOther.getPwd() != null
						&& this.getPwd().equals(castOther.getPwd())))
				&& ((this.getUserLogin() == castOther.getUserLogin()) || (this.getUserLogin() != null
						&& castOther.getUserLogin() != null && this.getUserLogin().equals(castOther.getUserLogin())))
				&& ((this.getTel() == castOther.getTel()) || (this.getTel() != null && castOther.getTel() != null
						&& this.getTel().equals(castOther.getTel())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())))
				&& ((this.getOnline() == castOther.getOnline()) || (this.getOnline() != null
						&& castOther.getOnline() != null && this.getOnline().equals(castOther.getOnline())))
				&& ((this.getLastOnlineTime() == castOther.getLastOnlineTime())
						|| (this.getLastOnlineTime() != null && castOther.getLastOnlineTime() != null
								&& this.getLastOnlineTime().equals(castOther.getLastOnlineTime())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getDeptId() == castOther.getDeptId()) || (this.getDeptId() != null
						&& castOther.getDeptId() != null && this.getDeptId().equals(castOther.getDeptId())))
				&& ((this.getDeptName() == castOther.getDeptName()) || (this.getDeptName() != null
						&& castOther.getDeptName() != null && this.getDeptName().equals(castOther.getDeptName())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
						&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getRoleName() == castOther.getRoleName()) || (this.getRoleName() != null
						&& castOther.getRoleName() != null && this.getRoleName().equals(castOther.getRoleName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getCreateTime() == null ? 0 : this.getCreateTime().hashCode());
		result = 37 * result + (getPwd() == null ? 0 : this.getPwd().hashCode());
		result = 37 * result + (getUserLogin() == null ? 0 : this.getUserLogin().hashCode());
		result = 37 * result + (getTel() == null ? 0 : this.getTel().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		result = 37 * result + (getOnline() == null ? 0 : this.getOnline().hashCode());
		result = 37 * result + (getLastOnlineTime() == null ? 0 : this.getLastOnlineTime().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getDeptId() == null ? 0 : this.getDeptId().hashCode());
		result = 37 * result + (getDeptName() == null ? 0 : this.getDeptName().hashCode());
		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getRoleName() == null ? 0 : this.getRoleName().hashCode());
		return result;
	}

}
