package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-9 12:39:57 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VTransNotBack generated by hbm2java
 */
@Entity
@Table(name = "v_trans_not_back", schema = "public")
public class VTransNotBack implements java.io.Serializable {

	private VTransNotBackId id;

	public VTransNotBack() {
	}

	public VTransNotBack(VTransNotBackId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bankCode", column = @Column(name = "bank_code", length = 4)),
			@AttributeOverride(name = "billUuid", column = @Column(name = "bill_uuid", length = 36)) })
	public VTransNotBackId getId() {
		return this.id;
	}

	public void setId(VTransNotBackId id) {
		this.id = id;
	}

}
