package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-9 12:39:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VUserViewResultLogId generated by hbm2java
 */
@Embeddable
public class VUserViewResultLogId implements java.io.Serializable {

	private String userId;
	private String deptId;
	private Date viewDat;
	private String userIp;
	private String billUuid;
	private String deptName;
	private String userName;

	public VUserViewResultLogId() {
	}

	public VUserViewResultLogId(String userId, String deptId, Date viewDat, String userIp, String billUuid,
			String deptName, String userName) {
		this.userId = userId;
		this.deptId = deptId;
		this.viewDat = viewDat;
		this.userIp = userIp;
		this.billUuid = billUuid;
		this.deptName = deptName;
		this.userName = userName;
	}

	@Column(name = "user_id", length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "dept_id", length = 36)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "view_dat", length = 35)
	public Date getViewDat() {
		return this.viewDat;
	}

	public void setViewDat(Date viewDat) {
		this.viewDat = viewDat;
	}

	@Column(name = "user_ip", length = 128)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "bill_uuid", length = 36)
	public String getBillUuid() {
		return this.billUuid;
	}

	public void setBillUuid(String billUuid) {
		this.billUuid = billUuid;
	}

	@Column(name = "dept_name", length = 128)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VUserViewResultLogId))
			return false;
		VUserViewResultLogId castOther = (VUserViewResultLogId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getDeptId() == castOther.getDeptId()) || (this.getDeptId() != null
						&& castOther.getDeptId() != null && this.getDeptId().equals(castOther.getDeptId())))
				&& ((this.getViewDat() == castOther.getViewDat()) || (this.getViewDat() != null
						&& castOther.getViewDat() != null && this.getViewDat().equals(castOther.getViewDat())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this.getUserIp() != null
						&& castOther.getUserIp() != null && this.getUserIp().equals(castOther.getUserIp())))
				&& ((this.getBillUuid() == castOther.getBillUuid()) || (this.getBillUuid() != null
						&& castOther.getBillUuid() != null && this.getBillUuid().equals(castOther.getBillUuid())))
				&& ((this.getDeptName() == castOther.getDeptName()) || (this.getDeptName() != null
						&& castOther.getDeptName() != null && this.getDeptName().equals(castOther.getDeptName())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getDeptId() == null ? 0 : this.getDeptId().hashCode());
		result = 37 * result + (getViewDat() == null ? 0 : this.getViewDat().hashCode());
		result = 37 * result + (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		result = 37 * result + (getBillUuid() == null ? 0 : this.getBillUuid().hashCode());
		result = 37 * result + (getDeptName() == null ? 0 : this.getDeptName().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		return result;
	}

}
