package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-2-2 15:03:25 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserMenuM generated by hbm2java
 */
@Entity
@Table(name = "v_user_menu_m", schema = "public")
public class VUserMenuM implements java.io.Serializable {

	private VUserMenuMId id;

	public VUserMenuM() {
	}

	public VUserMenuM(VUserMenuMId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", length = 4)),
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", length = 4)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 45)),
			@AttributeOverride(name = "desc", column = @Column(name = "desc", length = 45)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 45)) })
	public VUserMenuMId getId() {
		return this.id;
	}

	public void setId(VUserMenuMId id) {
		this.id = id;
	}

}
