package gov.cqaudit.finance.hibernate.entities;
// Generated 2018-1-30 16:21:58 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserViewResultLog generated by hbm2java
 */
@Entity
@Table(name = "v_user_view_result_log", schema = "public")
public class VUserViewResultLog implements java.io.Serializable {

	private VUserViewResultLogId id;

	public VUserViewResultLog() {
	}

	public VUserViewResultLog(VUserViewResultLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 36)),
			@AttributeOverride(name = "deptId", column = @Column(name = "dept_id", length = 36)),
			@AttributeOverride(name = "viewDat", column = @Column(name = "view_dat", length = 35)),
			@AttributeOverride(name = "userIp", column = @Column(name = "user_ip", length = 128)),
			@AttributeOverride(name = "billUuid", column = @Column(name = "bill_uuid", length = 36)),
			@AttributeOverride(name = "deptName", column = @Column(name = "dept_name", length = 128)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", length = 45)) })
	public VUserViewResultLogId getId() {
		return this.id;
	}

	public void setId(VUserViewResultLogId id) {
		this.id = id;
	}

}
