package gov.cqaudit.finance.hibernate.entites;
// Generated 2017-12-5 16:09:39 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BusinessSearchPar generated by hbm2java
 */
@Entity
@Table(name = "business_search_par", schema = "public")
public class BusinessSearchPar implements java.io.Serializable {

	private BusinessSearchParId id;

	public BusinessSearchPar() {
	}

	public BusinessSearchPar(BusinessSearchParId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "businessCode", column = @Column(name = "business_code", nullable = false, length = 4)),
			@AttributeOverride(name = "searchParCode", column = @Column(name = "search_par_code", nullable = false, length = 4)) })
	public BusinessSearchParId getId() {
		return this.id;
	}

	public void setId(BusinessSearchParId id) {
		this.id = id;
	}

}
