package gov.cqaudit.finance.hibernate.entites;
// Generated 2017-12-5 1:01:52 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MenuM generated by hbm2java
 */
@Entity
@Table(name = "menu_m", schema = "public")
public class MenuM implements java.io.Serializable {

	private MenuMId id;

	public MenuM() {
	}

	public MenuM(MenuMId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false, length = 4)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 45)),
			@AttributeOverride(name = "desc", column = @Column(name = "desc", length = 45)) })
	public MenuMId getId() {
		return this.id;
	}

	public void setId(MenuMId id) {
		this.id = id;
	}

}
