package gov.cqaudit.finance.hibernate.entites;
// Generated 2017-12-9 9:31:50 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDept generated by hbm2java
 */
@Entity
@Table(name = "sys_dept", schema = "public")
public class SysDept implements java.io.Serializable {

	private String deptUuid;
	private String deptName;

	public SysDept() {
	}

	public SysDept(String deptUuid) {
		this.deptUuid = deptUuid;
	}

	public SysDept(String deptUuid, String deptName) {
		this.deptUuid = deptUuid;
		this.deptName = deptName;
	}

	@Id

	@Column(name = "dept_uuid", unique = true, nullable = false, length = 36)
	public String getDeptUuid() {
		return this.deptUuid;
	}

	public void setDeptUuid(String deptUuid) {
		this.deptUuid = deptUuid;
	}

	@Column(name = "dept_name", length = 128)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

}
